plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "ir.seam.player"
    compileSdk = 36

    defaultConfig {
        applicationId = "ir.seam.player"
        minSdk = 26
        targetSdk = 36
        versionCode = 9
        versionName = "2.2.2"
    }

    // Stable CI signing key is restored/generated by GitHub Actions.
    // This keeps future debug APKs upgrade-compatible without uninstalling.
    signingConfigs {
        create("debugUpgrade") {
            storeFile = file("${rootProject.projectDir}/debug.keystore")
            storePassword = "seamplayer-ci-2026"
            keyAlias = "seamplayer"
            keyPassword = "seamplayer-ci-2026"
        }
    }
    buildTypes {
        getByName("debug") { signingConfig = signingConfigs.getByName("debugUpgrade") }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api"
    }
    buildFeatures { compose = true }
    packaging { resources.excludes += "/META-INF/{AL2.0,LGPL2.1}" }
    sourceSets["main"].res.srcDir(layout.buildDirectory.dir("generated/seam-res"))
}

tasks.register<Copy>("prepareSeamLogo") {
    from(rootProject.file("Logo.png"))
    into(layout.buildDirectory.dir("generated/seam-res/drawable"))
    rename { "seam_logo.png" }
}
tasks.named("preBuild") { dependsOn("prepareSeamLogo") }

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2026.06.01")
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.activity:activity-compose:1.11.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.9.3")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.9.3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    debugImplementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.media3:media3-exoplayer:1.11.0")
    implementation("androidx.media3:media3-session:1.11.0")
    implementation("androidx.media3:media3-ui:1.11.0")
}
